-- ----------------------------
-- Table structure for `cp_access`
-- ----------------------------
DROP TABLE IF EXISTS `cp_access`;
CREATE TABLE `cp_access` (
  `user_id` int(11) NOT NULL DEFAULT '0',
  `punish` tinyint(1) DEFAULT '0',
  `refund` tinyint(1) DEFAULT '0',
  `ban` tinyint(1) DEFAULT '0',
  `cplgeneral` tinyint(1) DEFAULT '0',
  `cplstaff` tinyint(1) DEFAULT NULL,
  `cplfaction` tinyint(1) DEFAULT NULL,
  `cplfamily` tinyint(1) DEFAULT NULL,
  `gladmin` tinyint(1) DEFAULT '0',
  `gladmingive` tinyint(1) DEFAULT NULL,
  `gladminpay` tinyint(1) DEFAULT NULL,
  `glban` tinyint(1) DEFAULT NULL,
  `glcontracts` tinyint(1) DEFAULT NULL,
  `glddedit` tinyint(1) DEFAULT NULL,
  `gldmpedit` tinyint(1) DEFAULT NULL,
  `glfaction` tinyint(1) DEFAULT NULL,
  `glfamily` tinyint(1) DEFAULT NULL,
  `glfmembercount` tinyint(1) DEFAULT NULL,
  `glgedit` tinyint(1) DEFAULT NULL,
  `glgifts` tinyint(1) DEFAULT NULL,
  `glhack` tinyint(1) DEFAULT NULL,
  `glhedit` tinyint(1) DEFAULT NULL,
  `glhouse` tinyint(1) DEFAULT NULL,
  `glkick` tinyint(1) DEFAULT NULL,
  `gllicenses` tinyint(1) DEFAULT NULL,
  `glmoderator` tinyint(1) DEFAULT NULL,
  `glmute` tinyint(1) DEFAULT NULL,
  `glpads` tinyint(1) DEFAULT NULL,
  `glpassword` tinyint(1) DEFAULT NULL,
  `glpay` tinyint(1) DEFAULT NULL,
  `glplayervehicle` tinyint(1) DEFAULT NULL,
  `glrpspecial` tinyint(1) DEFAULT NULL,
  `glsecurity` tinyint(1) DEFAULT NULL,
  `glsetvip` tinyint(1) DEFAULT NULL,
  `glshopconfirmedorders` tinyint(1) DEFAULT NULL,
  `glshoplog` tinyint(1) DEFAULT NULL,
  `glshoporders` tinyint(1) DEFAULT NULL,
  `glstats` tinyint(1) DEFAULT NULL,
  `glundercover` tinyint(1) DEFAULT NULL,
  `glvipnamechanges` tinyint(1) DEFAULT NULL,
  `glvipremove` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
